<?php
/**
 * Created by PhpStorm.
 * User: crlt_
 * Date: 2018/4/13
 * Time: 上午11:03
 */

namespace console\controllers;


use common\models\Post;
use const PHP_EOL;
use yii\console\Controller;

class HelloController extends Controller
{
    public $rev;

    public function options($actionID)
    {
        //return parent::options($actionID); // TODO: Change the autogenerated stub
        return ['rev'];
    }
    public function optionAliases()
    {
     //   return parent::optionAliases(); // TODO: Change the autogenerated stub
        return ['r'=>'rev'];
    }

    public function actionIndex()
    {
        if ($this->rev == 1) {
            echo strrev("hello world").PHP_EOL;
        } else {
            echo("hello world".PHP_EOL);
        }
    }

    public function actionList()
    {
        $posts = Post::find()->all();
        foreach ($posts as $aPost) {
            echo $aPost['title'] . PHP_EOL;
        }
    }

    public function actionWho($name)
    {
        echo("hello " . $name . PHP_EOL);
    }

    public function actionTwo($name1, $name2)
    {
        echo("hello " . $name1 . " and " . $name2 . PHP_EOL);
    }
}